config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'

  resources :stories

  root 'homepage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
	 validates :text, presence: true
                 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	
	def index
    	@stories = Story.all
  	end

	def show
    	@story = Story.find(params[:id])
  	end

	def new
    @story = Story.new
	end

	def edit
  		@story = Story.find(params[:id])
	end

	def create
 		@story = Story.new(story_params)
 
  	if @story.save
  		redirect_to @story
    else
      render 'new'
    end
	end
 
	def update
  		@story = Story.find(params[:id])
  		@story.update(story_params)
  		redirect_to @story
	end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
 
    redirect_to stories_path
  end


	private
  	def story_params
    	params.require(:story).permit(:text)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/homepage/index.html.erb
<h1>This is SOMNIUM - a dream archive! :-)</h1>
<%= link_to 'check out', controller: 'stories' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Somnium</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Dream Archive</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/stories">Dreams</a></li>
      </ul>
    </div>
  </div>
</nav>
   <div class="container">
  <%= yield %>
</div>
<footer>
  <div class="container">
    Somnium <%= Time.now.year %>
  </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_with model: @story, local: true do |form| %>

 <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@story.errors.count, "error") %> prohibited
        this story from being saved:
      </h2>
      <ul>
        <% @story.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/stories/edit.html.erb
<h1>Edit your story</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>All stories</h1>
 <%= link_to 'new story', new_story_path %>
<table>
  <tr>
    <th></th>
  </tr>
 
  <% @stories.each do |story| %>
    <tr>
      
      <td><%= story.text %></td>
      <td><%= link_to 'Show', story_path(story) %></td>
      <td><%= link_to 'Edit', edit_story_path(story) %></td>
      <td><%= link_to 'Destroy', story_path(story),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/stories/new.html.erb
<h1>Your new story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
 
<p>
  <strong>Text:</strong>
  <%= @story.text %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>